---
- hosts: kslave1
  become: yes
  tasks:
    - name: deploy PHP app docker container
      docker_container:
        image: 'phuongnl95/php-app:{{ tag }}'
        name: php-app
        state: started
        ports:
          - "8888:80"
